bchavez/Bogus

- Source/Bogus/Person.cs
Date "9/20/1992" does not parse in an en-GB locale and probably in many others. I have changed now the reference date to be relative.
> Fixed instantiating a Person in a non-US locale.

- Source/.nuget/Bogus.nuspec
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/packages.config
- Source/Bogus/Bogus.csproj
- Source/Bogus/Properties/AssemblyInfo.cs
- Source/Bogus/packages.config
- Source/Builder/Builder.csproj
- Source/Builder/packages.config
Implements #2 by upgrading and fixating the nuspec file for Bogus to be constraint to the major version of 7 from `Json.NET`
> upgrade to json.net 7

- build.bat
Small fix so that you can run build.bat from a vanilla console, and it turns ECHO off so commands are not echo'd.
> import vs env variables when running from vanilla cmd console

- Source/Bogus.Tests/NameTests.cs
- Source/Bogus/DataSets/Name.cs
- Source/Bogus/Database.cs
There were copy-paste bug with first_name and last_name picking.
Also FindName throwed exception on non-English locales due to lack of suffixes/postfixes defined.
Funny that unit test checked first name and last name the same. Now should be OK.
> Fixed lastname and empty list exception

- HISTORY.md
- Source/Bogus.Tests/InternetTests.cs
- Source/Bogus/DataSets/Internet.cs
Add new Ipv6 generator to Bogus. Feature parity with faker.js. Prep new `7.1.7` release.
> Add new Ipv6 generator to Bogus

- HISTORY.md
- README.md
- Source/Bogus.Tests/FluentTests.cs
- Source/Bogus/Faker[T].cs
Fixes #41, implements implicit operator on `Faker<T>`. :muscle:
The following is now possible on `Faker<T>`:
```csharp
var orderFaker = new Faker<Order>()
.RuleFor(o => o.OrderId, f => f.IndexVariable++)
.RuleFor(o => o.Item, f => f.Commerce.Product())
.RuleFor(o => o.Quantity, f => f.Random.Number(1,3));
Order testOrder = orderFaker;
testOrder.Dump();
/* OUTPUT:
{
"OrderId": 0,
"Item": "Computer",
"Quantity": 2
}
*/
//Explicit works too!
var anotherOrder = (Order)orderFaker;
```
> Fixes #41 implements implicit operator on Faker[T]. :muscle:

- HISTORY.md
- Source/Builder/build.fsx
Removing whitespace (indents/tabs/newlines) in locale `Bogus/data/*.json` files ***reduces*** Bogus' DLL and memory footprint about 40%.
Huge win for performance by stripping whitespace before we publish to **NuGet**.
However, we still want to keep whitespace when doing development to aid readability.
This PR does just that.
:briefcase: :necktie: ***["Taking care of business every day... Taking care of business every way..."](https://www.youtube.com/watch?v=mmwic9kFx2c)***
> Remove whitespace when publishing Bogus to NuGet

- Source/Bogus.Tests/RuleSetTests.cs
- Source/Bogus.Tests/StrictModeTests.cs
- Source/Bogus/IRuleSet.cs
I prefer the Rules((f,c))=>{}) style of adding actions in a batch. I added that to the interface to accommodate this style.
> Added Faker<T> Rules(Action<Faker, T> setActions) to IRuleSet

- HISTORY.md
- README.md
- Source/Bogus/Bogus.csproj
- Source/Bogus/Bson/Bson.cs
- Source/Bogus/Database.cs
- Source/Bogus/Extensions/ExtensionsForString.cs
- Source/Bogus/Platform/ExtensionsForType.cs
- Source/Bogus/Randomizer.cs
Re-enables **.NET Standard 1.3** targeting in **Bogus**.
Cutting `v21` release after this merge passes tests.
//cc @Mpdreamz 
Reference #100, #101, #94.
:car: :blue_car: ***["Let the good times roll..."](https://www.youtube.com/watch?v=7BDBzgHXf64)***
> Re-enable .NET Standard 1.3 targeting.

- Source/Bogus/DataSets/Images.cs
When using the Image API it is actually not possible to add the category because the if statement is wrong.
> Bugfix category not working for images

- Source/Bogus/DataSet.cs
Profiling an application that uses Bogus to generate thousands of entities indicates a lot of time being spent recreating the regular expression whenever `DataSet.ParseTokens()` is called.
By caching and compiling the regular expression, performance should improve considerably. According to the [official documentation](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.regex(v=vs.110).aspx):
> The Regex class is immutable (read-only) and thread safe. Regex objects can be created on any thread and shared between threads.
> Improve speed of DataSet.ParseTokens() 

- README.md
- Source/Bogus.Tests/ExtensionTests/ExtensionTest.cs
- Source/Bogus/Extensions/Portugal/ExtensionsForPortugal.cs
- Source/Bogus/Extensions/Portugal/TaxNumberGenerator.cs
Generate random Tax identification number (NIF and NIPC) for Portugal. Added Facts in the ExtensionTest.
> New Extension for Portugal

- Source/Benchmark/BenchGenerate.cs
- Source/Benchmark/Program.cs
- Source/Bogus/Extensions/ExtensionsForPropertyInfo.cs
- Source/Bogus/Faker[T].cs
Using the following Fake context to generate `10,000` items:
```csharp
FakerWithRules = new Faker<Project>()
.CustomInstantiator(f=> new Project())
.RuleFor(p=>p.Id, f => f.IndexGlobal)
.UseSeed(1337);
```
Old (SetValue):
|             Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
|------------------- |---------:|----------:|----------:|---------:|---------:|--------:|----------:|
| Generate_WithRules | 6.770 ms | 0.0624 ms | 0.0584 ms | 265.6250 | 109.3750 | 31.2500 |   1.55 MB |
New (Cached setter delegate):
|             Method |     Mean |     Error |    StdDev |    Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|------------------- |---------:|----------:|----------:|---------:|--------:|--------:|----------:|
| Generate_WithRules | 4.046 ms | …
> Use cached delegates to set property values rather than SetValue

- HISTORY.md
- Source/Bogus/Bogus.csproj
Hopefully this makes debugging **Bogus** easier for everyone.
Not a big fan of adding *beta* stuff to **Bogus** but it's a developer dependency; so it should be okay I guess.
Comparing `Bogus.0.0.677-ci.nupkg` and `Bogus.24.3.1.nupkg`:
* Adds about `61 KB` to the total **NuGet** package size.
---
Only real diff between `.nupkg`s is the commit attribute in the `.nuspec` file and `42 KB` PDBs in each TFM output folder.
```diff
diff --git "a/R:\\Bogus.24.3.1\\Bogus.nuspec" "b/R:\\Bogus.0.0.677-ci\\Bogus.nuspec"
index 50922dc..8e8139e 100644
--- "a/R:\\Bogus.24.3.1\\Bogus.nuspec"
+++ "b/R:\\Bogus.0.0.677-ci\\Bogus.nuspec"
@@ -32,20 +35,10 @@
* Added `nullWeight` parameter to `.OrNull()` extension method for weighted generation of null values.
* Added new `.OrDefault()` extension method. …
```
> Add Visual Studio SourceLink compatibility.

- README.md
This is the only heading that does not match the API type-hinting, I feel this would benefit future users who were also confused by not being able to find phonenumbers.
> Match heading to API usage ex: Faker.Phone.Phonenumber

- Source/Bogus.Tests/GitHubIssues/Issue134.cs
- Source/Bogus.Tests/GitHubIssues/Issue253.cs
- Source/Bogus/Faker[T].cs
Adds support for Faker<T>.RuleFor("prop", ...) and Faker<T>.Ignore("prop") where "prop" is a property or field name on `T`. This is helpful in situations where it might be necessary to set up a rule for non-public members; such as `protected` members.
Mostly renamed the existing `protected virtual RuleFor(string)` to `protected virutal RuleForInternal(string)`.
Then added `public virtual RuleFor(string)` which forwards calls to `RuleForInternal`; but before it does so, ensures that the underlying member exists (from the point of view of the `IBinder`).
After looking at the existing code; I found `.Ignore` checks the existence of the members on `T` at `.Ignore` invocation time.  Considering that we already do this for `.Ignore`, I added the same precondition constraint to …
> Fixes #253 Adds Support for RuleFor(string) and Ignore(string)

- Source/Bogus.Tests/GitHubIssues/PullRequest259.cs
- Source/Bogus/Faker[T].cs
I was trying to use `GenerateForever` and I noticed that the `ruleSets` parameter is not utilized.
> Fix GenerateForever to pass rulesets parameter

- Source/Benchmark/BenchRandomSubset.cs
- Source/Benchmark/BenchSsn.cs
- Source/Benchmark/BenchStringFill.cs
- Source/Benchmark/Program.cs
- Source/Bogus.Tests/GitHubIssues/Issue260.cs
- Source/Bogus.Tests/PersonTest.cs
- Source/Bogus/Extensions/UnitedStates/ExtensionsForUnitedStates.cs
Fixes #260  - SSNs generated by Bogus should now pass basic validation.
Benchmarked 3 Algorithms:
```csharp
[Benchmark]
public void SsnAlgo1()
{
var a = r.Int(1, 898);
if (a == 666) a++;
var b = r.Int(1, 99);
var c = r.Int(1, 9999);
var result = $"{a:000}-{b:00}-{c:0000}";
}
[Benchmark]
public void SsnAlgo2()
{
var a = r.Int(1, 898);
if (a == 666) a++;
var b = r.Int(1, 99);
var c = r.Int(1, 9999);
var result = string.Format("{0:000}-{1:00}-{2:0000}", a, b, c);
}
[Benchmark]
public void SsnAlgo3()
{
var x = r.Int();
// right shift all bits except fir the first 10 bits = 2^10 = 1024.
var a = (x >> (32 - 10)) % 898;
if (a == 0 || a == 666) a++;
// use the first 7 bits = 2^7 = 128
var b = (x & 0x7F);
if (b == 0) b++;
// last 2^14 = 16384, for last 4 digits of SSN
var c = (x >> 7) & 0x3FFF;
if …
```
> Fixes #260 - SSNs generated by Bogus should now pass basic validation

- Source/Bogus.Tests/GitHubIssues/PullRequest261.cs
- Source/Bogus/DataSets/Internet.cs
Hello.
I'm writing a networking library for C# and needed to test with random IPEndPoints, so I thought it'd be helpful to do a PR to add into Bogus.
Apologies for being unfamiliar with Fluent Validation, so I couldn't write the tests.
The minimum port you can have in an IPEndPoint is IPEndPoint.MinPort, which is 0. However 0 is a special case for port numbers and asks the operating system to allocate a available randomly assigned port. Therefore, I've used IPEndPoint.MinPort + 1 as the minimum value as the value of 0 would never be reasonably observed in any connection.
> Added ability to generate random IPv4 and IPv6 System.Net.IPEndPoints

- Source/Bogus.Tests/DataSetTests/CompanyTest.cs
- Source/Bogus.Tests/PersonTest.cs
- Source/Bogus/Extensions/Brazil/ExtensionsForBrazil.cs
Often developers need this data (cpf and cnpj) to be numeric, unformatted, that's what this implementation does.
> Add includeFormatSymbols for cnpj & cpf in brazil extensions

- README.md
- Source/Bogus.Tests/ExtensionTests/NorwegianExtensionTest.cs
- Source/Bogus/Extensions/Norway/ExtensionsForNorway.cs
This adds an extension method (`Person.Fødselsnummer()`) to `Bogus.Extensions.Norway` for generating Norwegian national identity numbers (fødselsnummer).
It generates numbers for people born between 1834 and 2039, for both men and women. It will throw an exception if the birth year is before or after the years mentioned.
> Add extension method for generating Norwegian national identity numbers.

- Source/Bogus.Tests/DataSetTests/ImageTest.cs
- Source/Bogus.Tests/GitHubIssues/Issue124.cs
- Source/Bogus.Tests/GitHubIssues/Issue260.cs
- Source/Bogus.Tests/RandomizerTest.cs
- Source/Bogus/Randomizer.cs
This PR proposes several enhancements to the implementation of Randomizer:
- It does away with the hard upper bound of `int.MaxValue - 1` in `Number`.
* If the caller specifies a `max` value less than `int.MaxValue`, then it simply adds one to it to make it inclusive.
* If the caller specifies `int.MaxValue`, then it can't add 1 to `max`, so instead it subtracts 1 from `min`, adding it back into the result.
* If the caller also specifies `int.MinValue` for min, then it can't do that either, so it takes two samples, one of which is in the range `int.MinValue`..`-1`, and the other of which is used to decide 50% of the time to invert all the bits, producing a number the range `0`..`int.MaxValue`. (This determination is not based on the least significant bit, which I understand to be the …
> Enhancements to Randomizer

- README.md
I split the example code into 3 blocks, so it's easier to read.
> Improving README.md docs: Without Fluent Syntax

- Source/Bogus.Tests/StrictModeTests.cs
- Source/Bogus/Faker[T].cs
Splitted from #338
Null reference expcetion when StrictMode(true) is used and no RuleFor() is called
> StrictMode(true) Fixing null reference exception

- Source/Bogus.Tests/DataSetTests/NameTests.cs
- Source/Bogus/DataSets/Name.cs
When instantiating a new Person for the spanish locale the generated name was always english. 
I have added condition to return First Names from the default list if the locale doesn´t support gendered names
> Fix first name generation for locales that don't support gender names

- README.md
This was creating additional nesting on the readme that was confusing.
It made methods appear as nested methods of siblings.
> Fixes inconsistent space vs tabs on readme

- Source/Bogus.Tests/DataSetTests/DateTest.cs
- Source/Bogus.Tests/DataSetTests/DateTest.net60.cs
- Source/Bogus/DataSets/Date.cs
- Source/Bogus/DataSets/Date.net60.cs
- Added Support to below methods for DateOnly and TimeOnly
- `PastDateOnly` - Make defaults consistent with Past() DateTime
- `SoonDateOnly` - Make defaults consistent with Soon() DateTime
- `FutureDateOnly` - Make defaults consistent with Future() DateTime
- `BetweenDateOnly` - Make defaults consistent with Between() DateTime
- `RecentDateOnly` - Make defaults consistent with Recent() DateTime
- `RecentTimeOnly` - Some time in the last 15 minutes
- `SoonTimeOnly` - Some time in the next 15 minutes
- `BetweenTimeOnly` - Some TimeOnly Between Start and End; always in a clockwise direction
- Added unit tests for each functionality
- Fixed ramifications of introduction of .NET 6 & C#10, those are
- Fixed ambiguity between `DistinctBy()` from MoreLinq and System.Linq. `DictinctBy()` is newly …
> New Feature: Random DateOnly and TimeOnly

- Source/Benchmark/BenchRandomSubset.cs
- Source/Bogus/Faker.cs
Probable typo. 
This makes sure that hovering over the method in IDE's has the relevant display for these exceptions. With the example tag, not even the name of the exception that was going to throw was visible.
> Fix docstring that used `example` tag instead of `exception`

- README.md
Hey @bchavez!
I recently wrote a blog post about Bogus and Entity Framework Core. You can read it here: https://stenbrinke.nl/blog/taking-ef-core-data-seeding-to-the-next-level-with-bogus/
I'd feel honored if it could be added to the README.
I took a look at the other blog posts that are already mentioned in the README, and I feel like mine really adds value when talking about determinism. Some blog posts avoid this topic which means that when you make any schema changes, issues like #457 arise. Because I had to bang my head against this issue for a little bit (which was my own fault ;-)) I thought it'd be worth adding to the README.
Let me know what you think! Any feedback you might have would be very welcome! 🙏
Thank you for creating such an amazing library!
> Add Sander ten Brinke's blog post about Bogus to README

- Source/Benchmark/BenchRandomSubset.cs
- Source/Bogus/Extensions/ExtensionsForCultureInfo.cs
This PR:
* Fixes a mistake introduced into XmlDoc comments in 5c830673f94.
* Adds a trailing comma to list in ExtensionsForCultureInfo.cs so that new rows can be added without involving an edit to the unrelated preceding row.
> Minor touchup

- Source/Builder/Utils.cs
Minor work on AssemblyInfo metadata; record `BuildTime` AssmeblyInfo.Metadata and make format parseable.
> Remove UTC prefix in infoVersion

- HISTORY.md
- README.md
- Source/Bogus.Tests/ExtensionTests/NorwegianExtensionTest.cs
- Source/Bogus.Tests/PersonTest.cs
- Source/Bogus/Extensions/ExtensionsForString.cs
- Source/Bogus/Extensions/Finland/ExtensionsForFinland.cs
- Source/Bogus/Extensions/Norway/ExtensionsForNorway.cs
Fixes #497; removes diacritics from API method names in Bogus; Improves AOT compatability
> Remove diacritics from method names in Bogus; fixes #497

- Source/Bogus/Extensions/Finland/ExtensionsForFinland.cs
There were three issues with calculating control character for Finnish personal identity code (henkilötunnus).
1. Three-digit part after birthdate was not taken into account when calculating it.
2. Invalid characters were not skipped.
3. Gender was ignored.
It was also (rarely) possible to get 000 or 001 as the number part, both of which invalid.
This also changes that the number part is always between 002-899. Numbers 900-999 do not exist "in the wild", they are strictly reserved for temporary identity codes.
There could of course be an option to also allow temporary codes, or generate only them. I can add them if you wish.
How the identity code is formed: https://dvv.fi/en/personal-identity-code
Fixes #392
> Fix incorrect generation for Finnish social security number

- Source/Bogus.Tests/DataSetTests/VehicleTest.cs
- Source/Bogus/DataSets/Vehicle.cs
The last appended random number segment of a VIN could sometimes yield an invalid VIN because the max allowed number value was 100000. This caused the returned VIN to have a length of 18 characters.
Without the fix, the new test case in this PR would produce an assertion exception:
```
Expected string with length 17, but found string "XTVJ5JFU2YBV100000" with length 18.
```
> Fixes VIN sometimes has 18 character length

- Source/Bogus.Tests/DataSetTests/VehicleTest.cs
- Source/Bogus/DataSets/Vehicle.cs
Adds an optional boolean to opt-in to generating a VIN using a more strict characterset.
> In 1981, the [National Highway Traffic Safety Administration](https://en.wikipedia.org/wiki/National_Highway_Traffic_Safety_Administration) of the United States standardized the format.[[1]](https://en.wikipedia.org/wiki/Vehicle_identification_number#cite_note-nhtsa1-1) It required all on-road vehicles sold to contain a 17-character VIN, which does not include the letters O (o), I (i), and Q (q) (to avoid confusion with numerals 0, 1, and 9).
Fixes #449
> Add option to generate strict VIN (exclusive characters I, O and Q)

- README.md
- Source/Bogus.Tests/ExtensionTests/SwedishExtensionTest.cs
- Source/Bogus/Extensions/Sweden/ExtensionsForSweden.cs
Government agencies, insurance companies and a few others have a vested interest in registering individuals that do not have a Swedish national  identity number. In these cases they can be given a collaboration number which basically follows the same format and rules with one notable exception; The "day" is offset by 60. This addition allows users to fake samordningsnummer.
> Added extension Samordningsnummer with unit tests

- Source/Bogus/Randomizer.cs
Address #528 by adding information in `Randomizer.cs`'s xml param docs about whether the passed-in number ranges are inclusive or exclusive.
All methods except for `Randomizer.Double()` and `Randomizer.Decimal()` had fully inclusive number ranges. Technically, `Randomizer.Float()` is also inclusive despite using `Randomizer.Double()` due to the rounding of `Convert.ToSingle()` ([fiddle](https://dotnetfiddle.net/QIEh0U))
> Docs: Add inclusive / exclusive number ranges documentation for Randomizer

- Source/Bogus.Tests/ExtensionTests/SwedishExtensionTest.cs
- Source/Bogus/Extensions/Sweden/ExtensionsForSweden.cs
For a Swedish Personnummer (social security number), the last digit is a Luhn-checksum. The second last digit is odd for a person with male legal gender and even for a person with female legal gender.
You can read about it here:
https://skatteverket.se/privat/folkbokforing/personnummer.4.3810a01c150939e893f18c29.html
The implementation in ExtensionsForSweden.cs was implemented the other way around for male/female.
This PR fixes the gender digit and the corresponding unit tests.
> Fix for issue #534: Gender-digit is incorrect for Swedish Personnummer generation

- README.md
Just noticed that README.md has a copy/paste error, stating that `Randomizer`'s `ULong` method returns a value between -128 and 127, like `SByte`. The XML docs in the code do not have this error, just the README.
> Correct the description of Random.ULong in README.md

- README.md
- Source/Bogus.Tests/ExtensionTests/BelgianExtensionTests.cs
- Source/Bogus/Extensions/Belgium/ExtensionsForBelgium.cs
This PR adds capability to generate Belgian national numbers ("rijksregisternummer" / RRN, "Numéro Nationale" or "Nationale Nummer" / NN in local languages) on a `Person` object
> Added extension method on Person to generate Belgian national number

- HISTORY.md
- Source/Bogus.Tests/GitHubIssues/Issue581.cs
- Source/Bogus/Randomizer.cs
> Fix for Randomizer.ULong() arithmetic overflow.

- .config/dotnet-tools.json
- .nuke/build.schema.json
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Builder/Build.cs
- Source/Builder/Builder.csproj
- Source/Builder/Utils.cs
Additional changes required for Builder / NUKE to build in .NET 9 on Linux. Follow up PR for #586
> Update Builder/Nuke to use .NET 9 SDK tooling and runtime.

- Source/Bogus.Tests/ExtensionTests/IranianExtensionTests.cs
- Source/Bogus/Extensions/Iran/ExtensionsForIran.cs
This pull request introduces a new feature to generate Iranian national number. The unit tests are also included.
- Added a new static class called `ExtensionsForIran` inside a new folder called `Iran` in the Extensions folder.
- Added a new extension method inside the `ExtensionsForIran` class called `IranianNationalNumber` to generate valid Iranian national number.
- Added a new class called `IranianExtensionTests` inside the ExtensionTests folder. This class contains four newly added methods described below 👇
1. `ValidateIranianNationalNumber` : This is responsible for validating any given national number via a specific algorithm and is used by other test methods.
2. `can_create_valid_iranian_national_number` : This will ensure the output matches the expected pattern and is actually a …
> Add extension method for generating Iranian national number

- Source/Bogus/Bson/Bson.cs
- Source/Bogus/DataSets/Finance.cs
- Source/Bogus/DataSets/System.cs
- Source/Bogus/Extensions/Brazil/ExtensionsForBrazil.cs
- Source/Bogus/Extensions/Canada/ExtensionsForCanada.cs
- Source/Bogus/Extensions/Denmark/ExtensionsForDenmark.cs
- Source/Bogus/Extensions/Finland/ExtensionsForFinland.cs
- Source/Bogus/Extensions/Iran/ExtensionsForIran.cs
- Source/Bogus/Extensions/Norway/ExtensionsForNorway.cs
- Source/Bogus/Extensions/Poland/ExtensionsForPoland.cs
- Source/Bogus/Extensions/Portugal/ExtensionsForPortugal.cs
- Source/Bogus/Extensions/Romania/ExtensionsForRomania.cs
- Source/Bogus/Extensions/Sweden/ExtensionsForSweden.cs
- Source/Bogus/Extensions/UnitedKingdom/ExtensionsForUnitedKingdom.cs
- Source/Bogus/Extensions/UnitedStates/ExtensionsForUnitedStates.cs
- Source/Bogus/Faker[T].Extensions.cs
- Source/Bogus/Premium/ContextHelper.cs
places where if it isnt that type, it would result in a null ref. so in the case where the type assumption is wrong, it is better to get a helpful exception about incorrect type, than a null ref
> fix incorrect as usages
