bchavez/Bogus

- README.md
- Source/Bogus.Tests/FluentTests.cs
- Source/Bogus.Tests/LoremTests.cs
- Source/Bogus.Tests/StrictModeTests.cs
- Source/Bogus/DataSets/Lorem.cs
Just some minor spelling corrections.
This library is amazing, I love it! Thanks!
> Corrects "Sentance" to "Sentence" etc.

- HISTORY.md
- Source/Bogus.Tests.Dnx/project.json
- Source/Bogus/project.json
- Source/Builder/build.fsx
- Source/global.json
:cat: :bee: [***"Orange buttercat... Chasing after... The crazy bee..."***](https://www.youtube.com/watch?v=4WO4oSsxlKs)
> .NET Core v1.0 RTM.

- HISTORY.md
- README.md
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/ValidationDeltaTests.cs
- Source/Bogus/Bogus.csproj
- Source/Bogus/Faker[T].cs
- Source/Bogus/ValidationException.cs
- Source/Bogus/ValidationResult.cs
Minor changes to exception formatting and unit tests expect `ValidationException`.
/cc @gdimauro
Reference: https://github.com/bchavez/Bogus/pull/37
> Supersedes PR #37. Squished commit history, and cleaned up PR.

- Source/Bogus.Tests/RuleSetTests.cs
- Source/Bogus/Rule.cs
> Allow rules to be overridden

- Source/Bogus/Faker.cs
This is a PR for this issue: https://github.com/bchavez/Bogus/issues/49
I only build the implementation, i did not add any tests as you can see.
> Add PickRandom overload to pick a subset of items from the list.

- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/README_Generator.cs
- Source/Bogus.Tests/packages.config
- Source/Bogus/Properties/AssemblyInfo.cs
- Source/Builder/build.fsx
Upgrade unit test infrastructure
> Upgrade unit test infrastructure

- Source/Bogus.Tests/GitHubIssues.cs
- Source/Bogus/Faker.cs
Current implementation of PickRandom is very slow on big collections.
I propose to implement PickRandom via shuffle
Results of test:
> PickRandom (2 from 2000). Elapsed: 00:00:06.9335806.
> ViaShuffle     (2 from 2000). Elapsed: 00:00:00.2456331.
> 
> PickRandom (10 from 2000). Elapsed: 00:00:08.0522107.
> ViaShuffle (10 from 2000). Elapsed: 00:00:00.3048799.
> 
> PickRandom (100 from 2000). Elapsed: 00:00:08.6209873.
> ViaShuffle (100 from 2000). Elapsed: 00:00:00.8475301.
> 
> PickRandom (500 from 2000). Elapsed: 00:00:09.7293146.
> ViaShuffle (500 from 2000). Elapsed: 00:00:02.8197884.
> 
> PickRandom (1000 from 2000). Elapsed: 00:00:10.7380362.
> ViaShuffle (1000 from 2000). Elapsed: 00:00:05.5229400.
> 
> PickRandom (1999 from 2000). Elapsed: 00:00:12.5223006.
> ViaShuffle (1999 from …
> Improve PickRandom performance

- README.md
I think seed has more esoteric meaning
> Updating to a better seed

- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/CloneTests.cs
- Source/Bogus.Tests/GitHubIssues/Issue100.cs
- Source/Bogus.Tests/RuleSetTests.cs
- Source/Bogus.Tests/StrictModeTests.cs
- Source/Bogus/DataSet.cs
- Source/Bogus/DataSets/Address.cs
- Source/Bogus/DataSets/Company.cs
- Source/Bogus/DataSets/Internet.cs
- Source/Bogus/DataSets/System.cs
- Source/Bogus/Extensions/ExtensionsForBrazil.cs
- Source/Bogus/Extensions/ExtensionsForCanada.cs
- Source/Bogus/Extensions/ExtensionsForDenmark.cs
- Source/Bogus/Extensions/ExtensionsForFinland.cs
- Source/Bogus/Extensions/ExtensionsForString.cs
- Source/Bogus/Extensions/ExtensionsForUnitedStates.cs
- Source/Bogus/Faker.cs
- Source/Bogus/Faker[T].cs
- Source/Bogus/Person.cs
- Source/Bogus/Randomizer.cs
- Source/Bogus/SeedNotifier[T].cs
Resolves #100.
This PR resolves a slowly brewing code smell in **Bogus**. My careless usage of `static` variables and sporadic sprinklings of `new Randomizer()` variables as a randomness source started to surface in reports about multi-threading issues and ultimately became a roadblock for adding new features like #100.
This PR resolves the matter by making determinism, as a concept, a first-class concern inside **Bogus**.
The way determinism is implemented in this PR is by keeping track of any dependent instances of data sources, at all levels (`DataSet`, `Facade`, and `Faker<T>`) that draw from a `Randomizer`. The overall architecture looks something like:
```
//Data sets with no other sources except Randomizer.
new Name
|
Randomizer
//Data sets that depend on other data sets as sources …
```
> Better Determinism and Faker.Clone()

- Source/Bogus.Tests/RandomizerTest.cs
- Source/Bogus/Randomizer.cs
Bool() method allows to specify probability to get a true value.
> Bool random generator

- Source/Bogus.Tests/DataSetTests/FinanceTest.cs
I like this project and thought about contributing. To start with an easy PR, I found some functions without unit tests and added the corresponding test cases. 
I added the following 4 tests:
- can_get_a_random_account_default()
- can_get_a_random_account_12()
- can_get_a_random_account_name()
- can_get_random_credit_card_cvv()
Hope that helps!
> Add more finance tests

- Source/Bogus.Tests/ExtensionTests/ExtensionTest.cs
- Source/Bogus/Extensions/ExtensionsForItaly/CodiceFiscaleBuilder.cs
- Source/Bogus/Extensions/ExtensionsForItaly/ExtensionsForItaly.cs
Method `CodiceFiscale()` added as an extension method to Persona and Finance classes.
Commit messages describe in great detail what's new.
This pull request closes #109 
Thanks,
Marcello.
> Italian fiscal code

- HISTORY.md
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/GitHubIssues/Issue114.cs
- Source/Bogus/DataSets/Finance.cs
- Source/Bogus/Extensions/Extras/FinanceExtensions.cs
> Credit card obfuscator and last four digits

- HISTORY.md
- Source/Bogus/BogusException.cs
- Source/Bogus/DataSet.cs
- Source/Bogus/Database.cs
- Source/Bogus/Faker.cs
- Source/Bogus/ILocaleAware.cs
- Source/Bogus/Person.cs
- Source/Bogus/Platform/ExtensionsForType.cs
- Source/Bogus/Premium/ContextHelper.cs
- Source/Bogus/Premium/License.cs
- Source/Bogus/Premium/LicenseVerifier.cs
- Source/Bogus/Premium/PremiumDataSet.cs
- Source/Bogus/SeedNotifier[T].cs
This PR lays the groundwork for extending **Bogus** with new APIs, DataSets (free and paid), and tooling.
The idea here is that datasets and APIs sourced from `faker.js` will always remain free and open-source. However, there are some use cases of **Bogus** that require more specialized data like #123.
The situation gets more real for authors of software applications in the healthcare industry where HIPAA regulations in the US have stringent requirements on medical and patient data. I think **Bogus** can help a lot here if we had the ability to generate bogus healthcare data like illnesses, diagnosis, procedures, drug, and other fake patient information, etc.
The datasets for these specializations will come in the form of additional **NuGet** packages that you can download off **NuGet**. …
> Premium License, Datasets, and Extensibility Refactoring

- README.md
This blog post demonstrates how Bogus can be used within the factory pattern and how to reproduce flaky tests that use generated data.
http://nance.io/leveling-up-your-dotnet-testing/
> Add blog post link to Readme

- Source/Bogus/Premium/ContextHelper.cs
isnt the new constraint redundant if a factory is required?
> remove redundant new

- Source/Bogus.Tests/DataSetTests/DateTest.cs
- Source/Bogus/DataSets/Date.cs
> Add DateTimeOffset

- Source/Bogus.Tests/ExtensionTests/ExtensionTest.cs
- Source/Bogus/Extensions/UnitedKingdom/ExtensionsForUnitedKingdom.cs
Does not follow strict rules for valid leading characters (i.e. D, F, I, Q, U or V are not valid)
> Add UK National Insurance Number

- Source/Bogus.Tests/DataSetTests/DateTest.cs
- Source/Bogus/DataSets/Date.cs
- Source/Bogus/Faker.cs
> add utcnow support

- Source/Bogus/DataSet.cs
DataSet  - type.Name.ToLower()
ToLower -> ToLowerInvariant
> Turkish Culture problem FIX Internet->ınternet

- README.md
The link does not exist anymore
> Removed obsolete link

- Source/Bogus/DataSets/Finance.cs
- Made the StringBuilder changes not have the previous commits
- Upgraded the code quality of the Finance class
Code Quality is mostly because of a combination of the CodeMaid and Roslyn analysers, it's both a blessing and a sin as it does add bulk to the PR.
Hoping this change is small enough.
> Replaced string with stringbuilder and code quality for finance

- Source/Bogus/DataSet.cs
- Added some documentation to the DataSet class.
- Changed some code to have high code quality.
Personally using [StyleCop](https://github.com/StyleCop/StyleCop)'s rules on how documentation should be done. I'd love to clean this class up more but I simply don't know enough about it.
> DataSet class documentation

- Source/Bogus/DataSets/Address.cs
- Rewrote the documentation
- Added some blank lines
- Changed formatting of if-statements
Nothing much this time around.
> Rewrote doc of Address class.

- Source/Bogus/DataSets/Company.cs
- Source/Bogus/DataSets/Database.cs
Basically only added the returns here, felt like it wasn't worth it's own PR so added Database as well.
> Company and Database documentation rework

- Source/Bogus/DataSets/Commerce.cs
- Rewrote the documentation
- Added some blank lines
- Changed formatting of if-statements
Not the best work as I don't understand some of the stuff going on. May revisit in the future
> Commerce doc rework

- Source/Bogus/DataSets/Rant.cs
Very simple and easy documentation
> Documentation for the Rant.cs class.

- Source/Bogus/Chars.cs
- Source/Bogus/ResourceHelper.cs
Special notice at the Chars.cs file, Hex said it was `a-z` and `A-Z` before.
My very limited knowledge (and the code) of hex says that's incorrect but I'll leave it up to you.
> Chars and resource doc

- Source/Bogus/DataSets/Internet.cs
> Cleaned up and rewrote documentation

- Source/Bogus/DataSets/Hacker.cs
- Source/Bogus/DataSets/PhoneNumbers.cs
Very basic cleanup and documentation.
> Hacker.cs and PhoneNumbers,cs Cleanup + Doc.

- Source/Bogus/DataSets/System.cs
- Renamed some variables to be more readable.
- Added returns documentation to methods.
- Added param documentation where possible.
> Added documentation and file name changes for the System class.

- HISTORY.md
- Source/Bogus/DataSets/Lorem.cs
Cleanup of the documentation and variable names within the Lorem DataSet class.
FYI I started work on an [extension](https://github.com/bartdebever/VideoGames.Bogus) to Bogus myself for personal use. If this goes well I'd be down to make more of these extensions might I need them in the future.
> Cleanup of the Lorem DataSet class.

- Source/Bogus/Bogus.csproj
- appveyor.yml
Add support for .snupkg NuGet Symbol Server Packages via SourceLink. https://github.com/appveyor/ci/issues/2753
> Add support for .snupkg NuGet Symbol Server Packages via SourceLink

- Source/Bogus/DataSets/Address.cs
The summary is incorrect. # defines the numeric characters and ? defines a letter. In summary it is the opposite :)
> The Summary Is Misleading

- Source/Bogus.Tests/ExtensionTests/SwedishExtensionTest.cs
- Source/Bogus/Extensions/Sweden/ExtensionsForSweden.cs
This adds generation of the swedish personumber
> add swedish personumber

- README.md
- Source/Bogus/DataSets/Date.cs
- Source/Bogus/DataSets/Finance.cs
- Source/Bogus/DataSets/System.cs
I'm not sure if you welcome typo/inconsitency PRs, I apologize in advance if you don't.
I was reading through the README and noticed a few things, a typo in code example in README.md and minor inconsitencies in API list with periods at the end.
> Fix a typo and minor inconsistencies in README.md

- Source/Bogus.Tests/GitHubIssues/Issue389.cs
- Source/Bogus/Binder.cs
Fixes #389 
Not very pretty, but doesn't seem to break anything...
> Fix setting property with private setter on base type

- README.md
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/README_Generator.cs
- Source/Bogus.sln
- Source/Directory.Build.props
- appveyor.yml
> Update Bogus build tooling; VS 2022, .NET 6 SDK, and C# 10

- Source/Bogus/Randomizer.cs
Refer to T.MinValue and T.MaxValue
> Unified documentation

- README.md
- Source/Bogus.Tests/Bogus.Tests.csproj
> Run tests only against LTS, STS, and FF

- .editorconfig
- .gitattributes
- README.md
- Source/Bogus.Tests/Bogus.Tests.csproj
- Source/Bogus.Tests/SchemaTests/EnLocaleSchemaTests.cs
- Source/Bogus.Tests/SchemaTests/EnLocaleSchemaTests.ensure_wellknown_en_locale_schema.verified.txt
Useful for detecting locale schema changes that will be needed for faker-js locale updates.
> Add snapshot test for en locale schema

- Source/Bogus.Tests/ExtensionTests/DanishExtentionTest.cs
- Source/Bogus.Tests/PersonTest.cs
- Source/Bogus/Extensions/Denmark/ExtensionsForDenmark.cs
Some older systems still use CPR number checksum validation. This updates the danish CPR number extension, to optionally create CPR numbers that can be validated against checksums.
Unit tests are also provided for the extension updates.
> Denmark extensions: Updates CPR number generator with checksum

- Source/Bogus.Tests/GitHubIssues/PullRequest510.cs
- Source/Bogus/Extensions/UnitedKingdom/ExtensionsForUnitedKingdom.cs
- Source/Bogus/Extensions/UnitedKingdom/VatRegistrationNumberType.cs
Added support for UK VAT registration numbers.
> Added support for UK VAT registration numbers.

- HISTORY.md
- Source/Bogus/Bogus.csproj
- Source/Bogus/Properties/AssemblyInfo.cs
Pack LICENSE file with Nuget package; also use ProjectIcon
> Pack LICENSE file with Nuget package; also use ProjectIcon

- Source/Bogus/Premium/License.cs
- Source/Bogus/Tokenizer.cs
> make License and Tokenizer static

- Source/Bogus.Tests/DataSetTests/InternetTests.cs
- Source/Bogus.Tests/GitHubIssues/Issue601.cs
- Source/Bogus/DataSets/Internet.cs
> Moves Avatar URL generation from deprecated cloudflare IPFS to public IPFS.IO
